snapblocks_discourse:
  snapblocks_enabled:
    default: false
    client: true
  block_style:
    client: true
    default: "snap"
    type: enum
    choices:
      - snap
      - snap-flat
      - scratch2
      - scratch3
      - scratch3-hc
  block_scale:
    client: true
    type: float
    default: 1
    min: 0.1
  zebra_coloring:
    client: true
    default: true
  block_wrap:
    client: true
    default: true
  show_spaces:
    client: true
    default: true
  enable_scratchblocks:
    client: true
    default: true
